//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::{
    file_data::Entity as FileData, file_metadata::Entity as FileMetadata, files::Entity as Files,
    files_tags::Entity as FilesTags, tags::Entity as Tags,
};
