//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tags")]
#[serde(rename_all = "camelCase")]
#[typeshare::typeshare]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::files_tags::Entity")]
    FilesTags,
}

impl Related<super::files_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FilesTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
